int32 task
int32 placerTask
int32 cameraSelect
int32 numAverages
float32 data1
float32 data2
float32 data3
---
int8 status
int32 cameraSelect
float32 data1
float32 data2
float32 data3
---
int8 not_used
