#ifndef PLACER_MESSAGE_DEF_H_
#define PLACER_MESSAGE_DEF_H_

namespace pap_common {

enum PROCESS {
	IDLE_STATE = 1,
	CALIBRATION_STATE = 2,
	GOTOBOX_STATE = 3,
	STARTPICKUP_STATE = 4,
	GOTOPCBCOMP_STATE = 5,
	PLACECOMPONENT_STATE = 6,
	HOMING_STATE = 7,
	INFO = 8,
        GOTO_STATE = 9,
        OFFSET_CALIBRATION = 10,
        RATIO_CALIBRATION = 11
//ERROR_STATE = 18
};

enum PLACER_STATUS {
	PLACER_IDLE = 1,
	PLACER_ACTIVE = 2,
	PLACER_FINISHED = 3,
	PLACER_ERROR = 4,
	DISPENSER_FINISHED = 5,
	DISPENSER_ERROR = 6,
	LEFT_TIP_UP = 7,
	RIGHT_TIP_UP = 8,
	LEFT_TIP_DOWN = 9,
	RIGHT_TIP_DOWN = 10
};

} // end namespace

#endif
